name: telegraph

services:
  app:
    container_name: telegraph
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: trace-app:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
